# permissions for end users to edit monitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-editor-role
rules:
- apiGroups:
  - datadog.jonnylangefeld.com
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datadog.jonnylangefeld.com
  resources:
  - monitors/status
  verbs:
  - get
